CREATE TABLE APPLICATION (
    ID NUMBER(19) PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    APIKEY VARCHAR2(100) NOT NULL UNIQUE,
    URL VARCHAR2(200) NOT NULL,
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE APPLICATION_SEQ START WITH 1 INCREMENT BY 1;
